
export const FETCH_MENU_REQUEST = 'menu/FETCH_MENU_REQUEST';
export const FETCH_MENU_SUCCESS = 'menu/FETCH_MENU_SUCCESS';
export const FETCH_MENU_ERROR = 'menu/FETCH_MENU_ERROR';
export const ADD_MENU_ITEM_SUCCESS = 'menu/ADD_MENU_ITEM_SUCCESS'
export const DELETE_MENU_ITEM_SUCCESS = 'menu/DELETE_MENU_ITEM_SUCCESS';
export const FETCH_CATEGORIES_SUCCESS = 'category/FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'category/FETCH_CATEGORIES_ERROR'
export const FETCH_ITEM_BY_CATEGORY_SUCCESS = 'category/FETCH_ITEM_BY_CATEGORY_SUCCESS'
export const CHANGE_FILTER = 'menu/CHANGE_FILTER'
export const GET_MENU_ITEM_REQUEST = 'item/GET_MENU_ITEM_REQUEST'
export const GET_MENU_ITEM_SUCCESS = 'item/GET_MENU_ITEM_SUCCESS'



